# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B5AV2PUUtiZ-3i91IuUlFXYk1naZo0K9
"""

# funciones
import math

def pedir_numero():
    return float(input("Ingresa un número: "))

def calcular_raiz_cuadrada(num):
    return math.sqrt(num)

def mostrar_resultado(resultado):
    print(f"La raíz cuadrada es: {resultado}")

# algoritmo principal
numero = pedir_numero()
resultado = calcular_raiz_cuadrada(numero)
mostrar_resultado(resultado)

