# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B5AV2PUUtiZ-3i91IuUlFXYk1naZo0K9
"""



#FUNCIONES
def tomar_Area():
  radio = float(input("escribe el area de la esfera"))
  return radio

def volumen_esfera(radio):
  pi = 3.14
  volumen =  (4/3) * pi * radio**3
  return volumen

def resultado(volumen):
  print("este es el volumen de tu esfera", volumen)


#ALGORITMO PRINCIPAL
radio = tomar_Area()
volumen = volumen_esfera(radio)
resultado(volumen)

