# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B5AV2PUUtiZ-3i91IuUlFXYk1naZo0K9
"""

def capturar_lado():
    lado = float(input("Ingresa la longitud del lado del cubo: "))
    return lado

def calcular_volumen_cubo(lado):
    volumen = lado ** 3
    return volumen

def mostrar_volumen(volumen):
    print("El volumen del cubo es:", volumen)

#algoritmo principal
lado = capturar_lado()
volumen = calcular_volumen_cubo(lado)
mostrar_volumen(volumen)

