# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B5AV2PUUtiZ-3i91IuUlFXYk1naZo0K9
"""

# funciones
def pedir_numero():
    return float(input("Ingresa un número: "))

def calcular_cuadrado(num):
    return num * num

def mostrar_resultado(resultado):
    print(f"El cuadrado es: {resultado}")

# algoritmo principal
numero = pedir_numero()
resultado = calcular_cuadrado(numero)
mostrar_resultado(resultado)

