# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B5AV2PUUtiZ-3i91IuUlFXYk1naZo0K9
"""

# funciones
def pedir_numero():
    return float(input("Ingresa un número: "))

def calcular_area_triangulo(base, altura):
    return (base * altura) / 2

def mostrar_resultado(resultado):
    print(f"El área del triángulo es: {resultado}")

# algoritmo principal
base = pedir_numero()
altura = pedir_numero()
resultado = calcular_area_triangulo(base, altura)
mostrar_resultado(resultado)

