# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B5AV2PUUtiZ-3i91IuUlFXYk1naZo0K9
"""



def tomar_altura():
  altura = float(input("ingrese la altura del rectangulo: "))
  return altura

def tomar_ancho():
  ancho = float(input("ingrese el ancho del rectangulo:"))
  return ancho

def calcular_Area():
  area = altura * ancho
  return area

#algotitmo principal
altura = tomar_altura()
ancho = tomar_ancho()
area = calcular_Area()
print("el area del rectangulo es:", area)

