# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B5AV2PUUtiZ-3i91IuUlFXYk1naZo0K9
"""

#funciones
def capturar_datos():
    radio = float(input("Ingrese el radio: "))
    altura = float(input("Ingrese la altura: "))
    return radio, altura

def calcular_volumen(radio, altura):
    volumen = (1/3) * 3.14* (radio ** 2) * altura
    return volumen

def mostrar_resultado(volumen):
    print("El volumen del cono es:", volumen)

#algoritmo principal
radio, altura = capturar_datos()
volumen = calcular_volumen(radio, altura)
mostrar_resultado(volumen)

