# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B5AV2PUUtiZ-3i91IuUlFXYk1naZo0K9
"""

#funciones
def capturar_datos_piramide():
    base = float(input("Ingresa la longitud de la base: "))
    ancho = float(input("Ingresa el ancho de la base: "))
    altura = float(input("Ingresa la altura de la pirámide: "))
    return base, ancho, altura

def calcular_volumen_piramide(base, ancho, altura):
    volumen = (base * ancho * altura) / 3
    return volumen

def mostrar_volumen(volumen):
    print("El volumen de la pirámide es:", volumen)

#algoritmo principal

base, ancho, altura = capturar_datos_piramide()
volumen = calcular_volumen_piramide(base, ancho, altura)
mostrar_volumen(volumen)

