# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B5AV2PUUtiZ-3i91IuUlFXYk1naZo0K9
"""

# funciones
def pedir_numero():
    return int(input("Ingresa la cantidad de horas: "))

def convertir_a_minutos(horas):
    return horas * 60

def mostrar_resultado(resultado):
    print(f"La cantidad de minutos es: {resultado}")

# algoritmo principal
horas = pedir_numero()
resultado = convertir_a_minutos(horas)
mostrar_resultado(resultado)

