# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B5AV2PUUtiZ-3i91IuUlFXYk1naZo0K9
"""

#funciones
def capturar_datos():
    base_mayor = float(input("Ingrese la base mayor: "))
    base_menor = float(input("Ingrese la base menor: "))
    altura = float(input("Ingrese la altura: "))
    return base_mayor, base_menor, altura

def calcular_area(base_mayor, base_menor, altura):
    area = ((base_mayor + base_menor) * altura) / 2
    return area

def mostrar_resultado(area):
    print("El área del trapecio es:", area)

# Algoritmo principal
base_mayor, base_menor, altura = capturar_datos()
area = calcular_area(base_mayor, base_menor, altura)
mostrar_resultado(area)

