# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B5AV2PUUtiZ-3i91IuUlFXYk1naZo0K9
"""

def capturar_litros():
    litros = float(input("Ingresa la cantidad en litros: "))
    return litros

def convertir_a_galones(litros):
    galones = litros / 3.78541
    return galones

def mostrar_conversion(galones):
    print("Equivale a", galones, "galones.")

#algoritmo principal
litros = capturar_litros()
galones = convertir_a_galones(litros)
mostrar_conversion(galones)

