# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B5AV2PUUtiZ-3i91IuUlFXYk1naZo0K9
"""

def capturar_datos():
    largo = float(input("Ingrese el largo: "))
    ancho = float(input("Ingrese el ancho: "))
    altura = float(input("Ingrese la altura: "))
    return largo, ancho, altura

def calcular_volumen(largo, ancho, altura):
    volumen = largo * ancho * altura34
    return volumen

def mostrar_resultado(volumen):
    print("El volumen del prisma rectangular es:", volumen)

largo, ancho, altura = capturar_datos()
volumen = calcular_volumen(largo, ancho, altura)
mostrar_resultado(volumen)

