# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B5AV2PUUtiZ-3i91IuUlFXYk1naZo0K9
"""

# funciones


def pedir_numero():
    return float(input("Ingresa el diámetro del círculo: "))

def calcular_circunferencia(diametro):
    return 3.14 * diametro

def mostrar_resultado(resultado):
    print(f"La circunferencia es: {resultado}")

# algoritmo principal
diametro = pedir_numero()
resultado = calcular_circunferencia(diametro)
mostrar_resultado(resultado)

