# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B5AV2PUUtiZ-3i91IuUlFXYk1naZo0K9
"""

# Funciónes
def capturar_lado():
    lado = float(input("Ingresa la longitud del lado del cuadrado: "))
    return lado

def calcular_area_cuadrado(lado):
    area = lado * lado
    return area

def mostrar_area(area):
    print("El área del cuadrado es:", area)

# Algoritmo principal

lado = capturar_lado()
area = calcular_area_cuadrado(lado)
mostrar_area(area)

