# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B5AV2PUUtiZ-3i91IuUlFXYk1naZo0K9
"""

# funciones
def pedir_numero():
    return float(input("Ingresa un número: "))

def mayor_de_dos(num1, num2):
    return num1 if num1 > num2 else num2

def mostrar_resultado(resultado):
    print(f"El mayor de los dos números es: {resultado}")

# algoritmo principal
numero1 = pedir_numero()
numero2 = pedir_numero()
resultado = mayor_de_dos(numero1, numero2)
mostrar_resultado(resultado)

