# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B5AV2PUUtiZ-3i91IuUlFXYk1naZo0K9
"""

#funciones
def capturar_datos():
    kilometros = float(input("Ingrese la distancia en kilómetros: "))
    return kilometros

def convertir_a_millas(kilometros):
    millas = kilometros * 0.62
    return millas

def mostrar_resultado(millas):
    print("Equivalente en millas:", millas)

#algoritmo principal
kilometros = capturar_datos()
millas = convertir_a_millas(kilometros)
mostrar_resultado(millas)

