# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B5AV2PUUtiZ-3i91IuUlFXYk1naZo0K9
"""

# funciones
def pedir_numero():
    ancho = float (input("ingrese el ancho del rectangulo"))
    longitud = float (input("ingrese la longitud del rectangulo"))
    return ancho, longitud

def calcular_area_rectangulo(longitud, ancho):
    return longitud * ancho

def mostrar_resultado(resultado):
    print(f"El área del rectángulo es: {resultado}")

# algoritmo principal
ancho, longitud = pedir_numero()
resultado = calcular_area_rectangulo(longitud, ancho)
mostrar_resultado(resultado)

