# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B5AV2PUUtiZ-3i91IuUlFXYk1naZo0K9
"""

#funciones
def capturar_datos():
    radio = float(input("Ingrese el radio: "))
    return radio

def calcular_area(radio):
    return 3.14 * (radio ** 2)

def mostrar_resultado(area):
    print("El área del círculo es:", area)

#algoritmo principal
radio = capturar_datos()
area = calcular_area(radio)
mostrar_resultado(area)