# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B5AV2PUUtiZ-3i91IuUlFXYk1naZo0K9
"""

import math

# Funciónes
def capturar_lado():
    lado = float(input("Ingresa la longitud del lado del hexágono: "))
    return lado

def calcular_area(lado):
    area = (3 * math.sqrt(3) / 2) * (lado ** 2)
    return area

def mostrar_resultado(area):
    print(f"El área del hexágono regular es: {area:.2f}")

# Algoritmo principal

lado = capturar_lado()
area = calcular_area(lado)
mostrar_resultado(area)

