# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B5AV2PUUtiZ-3i91IuUlFXYk1naZo0K9
"""



def tomar_altura():
  altura = int(input("toma la altura del triangulo: "))
  return altura

def tomar_base():
  base = int(input("toma la base del triangulo : "))
  return base

def calcular_area(altura,base):
  area = (altura*base)/2
  return area

altura = tomar_altura()
base = tomar_base()
area = calcular_area(altura, base)
print(area)