# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B5AV2PUUtiZ-3i91IuUlFXYk1naZo0K9
"""

def capturar_libras():
    libras = float(input("Ingresa la cantidad en libras: "))
    return libras

def convertir_a_kilogramos(libras):
    kilogramos = libras * 0.453592
    return kilogramos

def mostrar_conversion(kilogramos):
    print("Equivale a", kilogramos, "kilogramos.")

#algoritmo principal

libras = capturar_libras()
kilogramos = convertir_a_kilogramos(libras)
mostrar_conversion(kilogramos)

