# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B5AV2PUUtiZ-3i91IuUlFXYk1naZo0K9
"""

#funciones
def capturar_datos():
    dolares = float(input("Ingrese la cantidad en dólares: "))
    tasa = float(input("Ingrese la tasa de cambio (euros por dólar): "))
    return dolares, tasa

def convertir(dolares, tasa):
    euros = dolares * tasa
    return euros

def mostrar_resultado(euros):
    print("Equivalente en euros:", euros)

#algoritmo principal
dolares, tasa = capturar_datos()
euros = convertir(dolares, tasa)
mostrar_resultado(euros)

