# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B5AV2PUUtiZ-3i91IuUlFXYk1naZo0K9
"""

# funciones
def pedir_numero():
    return int(input("Ingresa un número: "))

def es_par_impar(num):
    return "par" if num % 2 == 0 else "impar"

def mostrar_resultado(resultado):
    print(f"El número es {resultado}")

# algoritmo principal
numero = pedir_numero()
resultado = es_par_impar(numero)
mostrar_resultado(resultado)

