# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B5AV2PUUtiZ-3i91IuUlFXYk1naZo0K9
"""

def capturar_datos_paralelogramo():
    base = float(input("Ingresa la base del paralelogramo: "))
    altura = float(input("Ingresa la altura del paralelogramo: "))
    return base, altura

def calcular_area_paralelogramo(base, altura):
    area = base * altura
    return area

def mostrar_area(area):
    print("El área del paralelogramo es:", area)

#algoritmo principal


base, altura = capturar_datos_paralelogramo()
area = calcular_area_paralelogramo(base, altura)
mostrar_area(area)

