# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B5AV2PUUtiZ-3i91IuUlFXYk1naZo0K9
"""

def capturar_datos_prisma():
    base = float(input("Ingresa la base del triángulo: "))
    altura_triangulo = float(input("Ingresa la altura del triángulo: "))
    longitud_prisma = float(input("Ingresa la longitud del prisma: "))
    return base, altura_triangulo, longitud_prisma

def calcular_volumen_prisma(base, altura_triangulo, longitud_prisma):
    volumen = (base * altura_triangulo / 2) * longitud_prisma
    return volumen

def mostrar_volumen(volumen):
    print("El volumen del prisma triangular es:", volumen)

#algoritmo principal

base, altura_triangulo, longitud_prisma = capturar_datos_prisma()
volumen = calcular_volumen_prisma(base, altura_triangulo, longitud_prisma)
mostrar_volumen(volumen)

