# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B5AV2PUUtiZ-3i91IuUlFXYk1naZo0K9
"""

#funciones
def capturar_datos():
    celsius = float(input("Ingrese la temperatura en °C: "))
    return celsius

def convertir_a_fahrenheit(celsius):
    fahrenheit = (celsius * 9/5) + 32
    return fahrenheit

def mostrar_resultado(fahrenheit):
    print("La temperatura en Fahrenheit es:", fahrenheit)

#algoritmo principal
celsius = capturar_datos()
fahrenheit = convertir_a_fahrenheit(celsius)
mostrar_resultado(Fahrenheit)

