# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B5AV2PUUtiZ-3i91IuUlFXYk1naZo0K9
"""

# funciones
def pedir_numero():
    return float(input("Ingresa la cantidad de dinero: "))

def calcular_interes(dinero):
    return dinero * 0.05

def mostrar_resultado(resultado):
    print(f"El 5% de interés es: {resultado}")

# algoritmo principal
dinero = pedir_numero()
resultado = calcular_interes(dinero)
mostrar_resultado(resultado)

