# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B5AV2PUUtiZ-3i91IuUlFXYk1naZo0K9
"""

#funciones
def capturar_pulgadas():
    pulgadas = float(input("Ingresa la cantidad en pulgadas: "))
    return pulgadas

def convertir_a_centimetros(pulgadas):
    centimetros = pulgadas * 2.54
    return centimetros

def mostrar_conversion(centimetros):
    print("Equivale a", centimetros, "centímetros.")

#algoritmo principal

pulgadas = capturar_pulgadas()
centimetros = convertir_a_centimetros(pulgadas)
mostrar_conversion(centimetros)

